apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hopskipdrive-lab
  region: us-west-2

iam:
  withOIDC: true

managedNodeGroups:
  - name: web-nodes-arm64
    instanceType: t4g.small
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    amiFamily: AmazonLinux2
    labels:
      workload: web
    tags:
      workload: web
